src/Entity/Etablissement.php
<?php

namespace App\Entity;

use App\Repository\EtablissementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtablissementRepository::class)]
class Etablissement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre_etudiants = null;

    #[ORM\OneToMany(mappedBy: 'etablissement', targetEntity: Etudiant::class, orphanRemoval: true)]
    private Collection $etudiantss;

    public function __construct()
    {
        $this->etudiantss = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNombreEtudiants(): ?string
    {
        return $this->nombre_etudiants;
    }

    public function setNombreEtudiants(string $nombre_etudiants): static
    {
        $this->nombre_etudiants = $nombre_etudiants;

        return $this;
    }

    /**
     * @return Collection<int, Etudiant>
     */
    public function getEtudiantss(): Collection
    {
        return $this->etudiantss;
    }

    public function addEtudiantss(Etudiant $etudiantss): static
    {
        if (!$this->etudiantss->contains($etudiantss)) {
            $this->etudiantss->add($etudiantss);
            $etudiantss->setEtablissement($this);
        }

        return $this;
    }

    public function removeEtudiantss(Etudiant $etudiantss): static
    {
        if ($this->etudiantss->removeElement($etudiantss)) {
            // set the owning side to null (unless already changed)
            if ($etudiantss->getEtablissement() === $this) {
                $etudiantss->setEtablissement(null);
            }
        }

        return $this;
    }
}

src/Form/EtablissementType.php
<?php

namespace App\Form;

use App\Entity\Etablissement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtablissementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('nombre_etudiants')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Etablissement::class,
        ]);
    }
}

src/Controller/EtablissementController.php
<?php

namespace App\Controller;

use App\Entity\Etablissement;
use App\Form\EtablissementType;
use App\Repository\EtablissementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/etablissement')]
class EtablissementController extends AbstractController
{
    #[Route('/', name: 'app_etablissement_index', methods: ['GET'])]
    public function index(EtablissementRepository $etablissementRepository): Response
    {
        return $this->render('etablissement/index.html.twig', [
            'etablissements' => $etablissementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_etablissement_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $etablissement = new Etablissement();
        $form = $this->createForm(EtablissementType::class, $etablissement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($etablissement);
            $entityManager->flush();

            return $this->redirectToRoute('app_etablissement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('etablissement/new.html.twig', [
            'etablissement' => $etablissement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_etablissement_show', methods: ['GET'])]
    public function show(Etablissement $etablissement): Response
    {
        return $this->render('etablissement/show.html.twig', [
            'etablissement' => $etablissement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_etablissement_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Etablissement $etablissement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EtablissementType::class, $etablissement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_etablissement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('etablissement/edit.html.twig', [
            'etablissement' => $etablissement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_etablissement_delete', methods: ['POST'])]
    public function delete(Request $request, Etablissement $etablissement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$etablissement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($etablissement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_etablissement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/etablissement/_delete_form.html.twig
<form method="post" action="{{ path('app_etablissement_delete', {'id': etablissement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etablissement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/etablissement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Etablissement{% endblock %}

{% block body %}
    <h1>Edit Etablissement</h1>

    {{ include('etablissement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_etablissement_index') }}">back to list</a>

    {{ include('etablissement/_delete_form.html.twig') }}
{% endblock %}

templates/etablissement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etablissement index{% endblock %}

{% block body %}
    <h1>Etablissement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Nombre_etudiants</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for etablissement in etablissements %}
            <tr>
                <td>{{ etablissement.id }}</td>
                <td>{{ etablissement.nom }}</td>
                <td>{{ etablissement.nombreEtudiants }}</td>
                <td>
                    <a href="{{ path('app_etablissement_show', {'id': etablissement.id}) }}">show</a>
                    <a href="{{ path('app_etablissement_edit', {'id': etablissement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_etablissement_new') }}">Create new</a>
{% endblock %}

templates/etablissement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Etablissement{% endblock %}

{% block body %}
    <h1>Create new Etablissement</h1>

    {{ include('etablissement/_form.html.twig') }}

    <a href="{{ path('app_etablissement_index') }}">back to list</a>
{% endblock %}

templates/etablissement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etablissement{% endblock %}

{% block body %}
    <h1>Etablissement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ etablissement.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ etablissement.nom }}</td>
            </tr>
            <tr>
                <th>Nombre_etudiants</th>
                <td>{{ etablissement.nombreEtudiants }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_etablissement_index') }}">back to list</a>

    <a href="{{ path('app_etablissement_edit', {'id': etablissement.id}) }}">edit</a>

    {{ include('etablissement/_delete_form.html.twig') }}
{% endblock %}